

spring.datasource.url=jdbc:mysql://localhost:3306/sportify?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=

# Server port
server.port=8080


# C\u00c3\u00a1\u00c2\u00ba\u00c2\u00a5u h\u00c3\u0083\u00c2\u00acnh Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.web.pageable.default-page-size=4
spring.data.web.pageable.max-page-size=100
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.main.allow-circular-references=true
spring.session.store-type=none

# C\u00e1\u00ba\u00a5u h\u00c3\u00acnh g\u00e1\u00bb\u00adi mail 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trungduc17032005@gmail.com
spring.mail.password=


gemini.api.key=...


spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com